### ISSUE TITLE
With Macvlan RDMA doesn't work across leaf switches

### ISSUE THREAD

**Issue by kidlj** [Mellanox/k8s-rdma-shared-dev-plugin#119]
We have 64 nodes where each has 4 RoCE devices, we deployed this shared device plugin and configured 4 MacvlanNetwork, as listed below.

```yaml
apiVersion: mellanox.com/v1alpha1
kind: MacvlanNetwork
metadata:
  name: macvlannetwork-1
spec:
  networkNamespace: "default"
  master: "roce10"
  mode: "bridge"
  mtu: 1500
  ipam: |
    {
      "type": "whereabouts",
      "datastore": "kubernetes",
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig"
      },
      "range": "192.168.2.0/24",
      "exclude": [
       "192.168.2.0/32",
       "192.168.2.1/32"
      ],
      "log_file" : "/var/log/whereabouts.log",
      "log_level" : "info",
      "gateway": "192.168.2.1"
    }
```

If 2 pods that reside on 2 nodes that are on the same leaf switch, the communication works. However, if the 2 nodes are spread across 2 leaf switches, the communication fails.

Does this device plugin with MacvlanNetwork setup work across switches? Thanks for any help.
